public class BeginnerExercises {

    public static void main(String[] args) {

        // 1. Declara una variable de tipo String y asígnale tu nombre.
        String nombre = "Sergio";

        // 2. Crea una variable de tipo int y asígnale tu edad.
        int edad = 12;

        // 3. Crea una variable double con tu altura en metros.
        double altura = 1.45;

        // 4. Declara una variable de tipo boolean que indique si te gusta programar.
        boolean mayor_edad = false;

        // 5. Declara una constante con tu email.
        const String email = "pepe@lopez.com";

        // 6. Crea una variable de tipo char y guárdale tu inicial.
        char inicial = 'S';

        // 7. Declara una variable de tipo String con tu localidad, y a continuación cambia su valor y vuelve a imprimirla.
        String localidad = "Zaragoza";
        localidad = "Huesca";
        System.out.println(localidad);

        // 8. Crea una variable int llamada a, otra b, e imprime la suma de ambas.
        int a = 2;
        int b = 8;
        System.out.println(localidad);

        // 9. Imprime el tipo de dos variables creadas anteriormente.
        System.out.println(type(a), type(localidad));

        // 10. Intenta declarar una variable sin inicializarla y luego asígnale un valor antes de imprimirla.
    }
}